; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:96b_nitrogen]
platform = nordicnrf52
framework = zephyr
board = 96b_nitrogen

[env:adafruit_feather_nrf52832]
platform = nordicnrf52
framework = zephyr
board = adafruit_feather_nrf52832

[env:adafruit_feather_nrf52840]
platform = nordicnrf52
framework = zephyr
board = adafruit_feather_nrf52840

[env:adafruit_ledglasses_nrf52840]
platform = nordicnrf52
framework = zephyr
board = adafruit_ledglasses_nrf52840

[env:bbcmicrobit_v2]
platform = nordicnrf52
framework = zephyr
board = bbcmicrobit_v2

[env:electronut_blip]
platform = nordicnrf52
framework = zephyr
board = electronut_blip

[env:electronut_papyr]
platform = nordicnrf52
framework = zephyr
board = electronut_papyr

[env:holyiot_yj16019]
platform = nordicnrf52
framework = zephyr
board = holyiot_yj16019

[env:laird_bl652_dvk]
platform = nordicnrf52
framework = zephyr
board = laird_bl652_dvk

[env:laird_bl653_dvk]
platform = nordicnrf52
framework = zephyr
board = laird_bl653_dvk

[env:laird_bl654_dvk]
platform = nordicnrf52
framework = zephyr
board = laird_bl654_dvk

[env:laird_pinnacle_100_dvk]
platform = nordicnrf52
framework = zephyr
board = laird_pinnacle_100_dvk

[env:nrf52_dk]
platform = nordicnrf52
framework = zephyr
board = nrf52_dk

[env:nrf52832_mdk]
platform = nordicnrf52
framework = zephyr
board = nrf52832_mdk

[env:nrf52833_dk]
platform = nordicnrf52
framework = zephyr
board = nrf52833_dk

[env:nrf52840_dk]
platform = nordicnrf52
framework = zephyr
board = nrf52840_dk

[env:nrf52840_mdk]
platform = nordicnrf52
framework = zephyr
board = nrf52840_mdk

[env:particle_argon]
platform = nordicnrf52
framework = zephyr
board = particle_argon

[env:particle_boron]
platform = nordicnrf52
framework = zephyr
board = particle_boron

[env:particle_xenon]
platform = nordicnrf52
framework = zephyr
board = particle_xenon

[env:redbear_blenano2]
platform = nordicnrf52
framework = zephyr
board = redbear_blenano2

[env:reel_board]
platform = nordicnrf52
framework = zephyr
board = reel_board

[env:reel_board_v2]
platform = nordicnrf52
framework = zephyr
board = reel_board_v2

[env:ruuvitag]
platform = nordicnrf52
framework = zephyr
board = ruuvitag

[env:thingy_52]
platform = nordicnrf52
framework = zephyr
board = thingy_52

[env:ublox_bmd345eval_nrf52840]
platform = nordicnrf52
framework = zephyr
board = ublox_bmd345eval_nrf52840

[env:vbluno52]
platform = nordicnrf52
framework = zephyr
board = vbluno52
